//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crud_application.db_context
{
    using System;
    using System.Collections.Generic;
    
    public partial class emptable
    {
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public Nullable<int> mobile { get; set; }
        public string dept { get; set; }
        public Nullable<int> sal { get; set; }
        public Nullable<int> zip { get; set; }
    }
}
